const PROJECTS = [
  {
    id: "801-studios",
    title: "801 Family Studios",
    type: "website",
    genre: "Studio · Production",
    location: "Salt Lake City, UT",
    url: "https://www.801familystudios.com/",
    accent: "#14b8a6",
    accentAlt: "#f59e0b",
    previewFile: "801-studios-2025.jpg",
    previewPosition: "top center",
    description: "Where artists feel at home — recording, management, booking, and full-service studio offerings in one polished hub.",
    tags: ["Studio", "Services", "Artist management"],
  },
  {
    id: "one-heart",
    title: "Magi & The One Heart Orchestra",
    type: "website",
    genre: "Orchestral · Spiritual",
    location: "Utah",
    url: "https://www.oneheartorchestra.com/",
    accent: "#c77dff",
    accentAlt: "#7b2cbf",
    description: "Immersive artist presence for a large ensemble with cinematic tone and booking flow.",
    tags: ["Orchestra", "Events", "Booking"],
  },
  {
    id: "alley-kats",
    title: "The Alley Kats",
    type: "website",
    genre: "Wyoming Reggae",
    location: "Wyoming",
    url: "https://www.thealleykatsvibe.com",
    accent: "#06d6a0",
    accentAlt: "#118ab2",
    description: "Full band site with events, media, EPK, merch, and contact — island vibes, live energy.",
    tags: ["Reggae", "Merch", "EPK link"],
  },
  {
    id: "dub-nectar",
    title: "Dub Nectar",
    type: "website",
    genre: "Reggae · Funk",
    location: "Utah",
    url: "https://www.dubnectar.com/",
    accent: "#ffd166",
    accentAlt: "#ef476f",
    description: "Live dub and funk grooves — events, media, and press kit in one polished package.",
    tags: ["Reggae", "Funk", "Events"],
  },
  {
    id: "charles-wilson",
    title: "Charles Wilson",
    type: "website",
    genre: "Soul · R&B",
    location: "National",
    url: "https://charleswilsonsoul.net/",
    accent: "#e63946",
    accentAlt: "#ffd700",
    description: "Crown Prince of Soul — elegant artist site built for legacy, performance, and booking.",
    tags: ["Soul", "Artist", "Legacy"],
  },
  {
    id: "tribe-of-i",
    title: "Tribe of I",
    type: "epk",
    genre: "Reggae Rock",
    location: "Salt Lake City, UT",
    url: "https://dbaileyfam.github.io/TribeofIEPK/",
    accent: "#2ec4b6",
    accentAlt: "#ff9f1c",
    description: "Festival-ready EPK with bio, Spotify embed, poster gallery, and press assets.",
    tags: ["EPK", "Posters", "Booking"],
  },
  {
    id: "the-pearls",
    title: "The Pearls",
    type: "epk",
    genre: "Indie · Alt-Rock",
    location: "Casper, WY",
    url: "https://dbaileyfam.github.io/ThePearlsEPK/",
    accent: "#90e0ef",
    accentAlt: "#caf0f8",
    description: "Pearl-toned press kit with events, video reels, and downloadable press photos.",
    tags: ["EPK", "Video", "Press photos"],
  },
  {
    id: "the-unaffected",
    title: "The Unaffected",
    type: "epk",
    genre: "Hard Rock · Metal-leaning",
    location: "Salt Lake City, UT",
    url: "https://dbaileyfam.github.io/theunaffectedepk/",
    accent: "#ff006e",
    accentAlt: "#8338ec",
    description: "High-impact rock EPK — Whisky a Go Go highlights, logos, and book-us CTA.",
    tags: ["EPK", "Rock", "Live photos"],
  },
  {
    id: "sun-divide",
    title: "Sun Divide",
    type: "epk",
    genre: "Reggae · Rock",
    location: "Salt Lake City, UT",
    url: "https://dbaileyfam.github.io/SunDivide/",
    accent: "#f9c74f",
    accentAlt: "#f3722c",
    description: "Festival-ready EPK with bio, streaming, press quotes, show dates, and downloadable press assets.",
    tags: ["EPK", "Press kit", "Stage plot"],
  },
];

/** Graphic design posters — pairs with 801 Family Studios Graphic Design for Bands. */
const POSTERS = [
  {
    id: "sawdust-and-strings",
    title: "Sawdust & Strings",
    category: "Brand identity",
    image: "sawdust-and-strings.png",
    description: "Rustic brand composite for a handcrafted instruments identity — wood, guitars, and portrait compositing.",
  },
  {
    id: "black-friday-reggae-party",
    title: "Black Friday Reggae Party",
    category: "Show flyer",
    image: "black-friday-reggae-party.png",
    description: "Psychedelic mountain night flyer for Funk & Gonzo, Dub Nectar, and Fear & Loathing at Quarters Downtown.",
  },
  {
    id: "headshine-dub-nectar",
    title: "Headshine × Dub Nectar",
    category: "Show flyer",
    image: "headshine-dub-nectar-july23.png",
    description: "Bold retro show poster for Redemption Bar and Grill — July 23 in Herriman.",
  },
  {
    id: "dublime-tribute",
    title: "Dublime Tribute",
    category: "Show flyer",
    image: "dublime-tribute.png",
    description: "Sublime tribute night with Dub Nectar and Ashlie Longo at A Bar Named Sue — dual-date promo.",
  },
  {
    id: "drum-lessons",
    title: "Drum Lessons",
    category: "Studio promo",
    image: "drum-lessons.png",
    description: "High-contrast lesson promo for Michael Bailey at 801 Family Studios — trial CTA and QR.",
  },
  {
    id: "black-friday-story",
    title: "Black Friday · Story",
    category: "Social story",
    image: "black-friday-reggae-story.png",
    description: "Minimal 9:16 story graphic for the Black Friday Reggae Party — flat landscape and clean type.",
  },
];
